 SELECT distinct
  dbamv.same.nr_matricula_same,
  dbamv.PACIENTE.CD_PACIENTE,
  dbamv.PACIENTE.NM_PACIENTE,
  dbamv.AVISO_CIRURGIA.CD_AVISO_CIRURGIA,
  dbamv.AVISO_CIRURGIA.VL_TEMPO_PREVISTO
FROM
  dbamv.PACIENTE, 
  dbamv.AVISO_CIRURGIA,
  dbamv.same 
  WHERE dbamv.PACIENTE.CD_PACIENTE = '135456'
  AND dbamv.AVISO_CIRURGIA.CD_PACIENTE = dbamv.PACIENTE.CD_PACIENTE 
  AND DBAMV.PACIENTE.CD_PACIENTE = DBAMV.SAME.CD_PACIENTE (+)
